---
- name: Setup Openmrs
  hosts: all
  user: root

- name: Setup Appservers
  hosts: appservers
  user: root

  roles:
    - java
    - tomcat
    - openmrs

- name: Setup DB servers
  hosts: dbservers
  user: root

  roles:
    - mysql

- name: Setup webservers
  hosts: webservers
  user: root

#  roles:
#    - apache
